export const players = [
  {
    fav: true,
    name: 'Lionel Messi',
    club: 'Inter Miami',
    position: 'Delantero',
    country: 'Argentina',
    age: 36,
    goals: 12,
    assists: 10,
    rating: 9.3,
  },
  {
    fav: false,
    name: 'Cristiano Ronaldo',
    club: 'Al Nassr',
    position: 'Delantero',
    country: 'Portugal',
    age: 39,
    goals: 14,
    assists: 4,
    rating: 8.9,
  },
  {
    fav: true,
    name: 'Kylian Mbappé',
    club: 'Paris Saint-Germain',
    position: 'Delantero',
    country: 'Francia',
    age: 25,
    goals: 28,
    assists: 11,
    rating: 9.1,
  },
  {
    fav: false,
    name: 'Kevin De Bruyne',
    club: 'Manchester City',
    position: 'Centrocampista',
    country: 'Bélgica',
    age: 32,
    goals: 8,
    assists: 17,
    rating: 8.8,
  },
  {
    fav: false,
    name: 'Erling Haaland',
    club: 'Manchester City',
    position: 'Delantero',
    country: 'Noruega',
    age: 23,
    goals: 34,
    assists: 5,
    rating: 9.0,
  },
  {
    fav: false,
    name: 'Neymar Jr.',
    club: 'Paris Saint-Germain',
    position: 'Delantero',
    country: 'Brasil',
    age: 31,
    goals: 13,
    assists: 12,
    rating: 8.7,
  },
  {
    fav: true,
    name: 'Luis Suárez',
    club: 'Grêmio',
    position: 'Delantero',
    country: 'Uruguay',
    age: 37,
    goals: 18,
    assists: 6,
    rating: 8.4,
  },
  {
    fav: false,
    name: 'Jude Bellingham',
    club: 'Real Madrid',
    position: 'Centrocampista',
    country: 'Inglaterra',
    age: 20,
    goals: 10,
    assists: 7,
    rating: 8.6,
  },
  {
    fav: false,
    name: 'Vinícius Júnior',
    club: 'Real Madrid',
    position: 'Delantero',
    country: 'Brasil',
    age: 23,
    goals: 22,
    assists: 9,
    rating: 8.9,
  },
  {
    fav: false,
    name: 'Luka Modrić',
    club: 'Real Madrid',
    position: 'Centrocampista',
    country: 'Croacia',
    age: 38,
    goals: 4,
    assists: 8,
    rating: 8.2,
  },
  {
    fav: false,
    name: 'Karim Benzema',
    club: 'Al Ittihad',
    position: 'Delantero',
    country: 'Francia',
    age: 35,
    goals: 21,
    assists: 6,
    rating: 8.5,
  },
  {
    fav: true,
    name: 'Robert Lewandowski',
    club: 'Barcelona',
    position: 'Delantero',
    country: 'Polonia',
    age: 35,
    goals: 23,
    assists: 4,
    rating: 8.7,
  },
  {
    fav: false,
    name: 'Karim Mbappé',
    club: 'Paris Saint-Germain',
    position: 'Delantero',
    country: 'Francia',
    age: 25,
    goals: 28,
    assists: 11,
    rating: 9.1,
  },
  {
    fav: false,
    name: 'Trent Alexander-Arnold',
    club: 'Liverpool',
    position: 'Defensa',
    country: 'Inglaterra',
    age: 24,
    goals: 5,
    assists: 18,
    rating: 8.4,
  },
  {
    fav: false,
    name: 'Pedri',
    club: 'Barcelona',
    position: 'Centrocampista',
    country: 'España',
    age: 21,
    goals: 7,
    assists: 10,
    rating: 8.5,
  },
  {
    fav: false,
    name: 'Virgil van Dijk',
    club: 'Liverpool',
    position: 'Defensa',
    country: 'Países Bajos',
    age: 32,
    goals: 5,
    assists: 2,
    rating: 8.3,
  },
  {
    fav: true,
    name: 'Harry Kane',
    club: 'Bayern Múnich',
    position: 'Delantero',
    country: 'Inglaterra',
    age: 30,
    goals: 26,
    assists: 9,
    rating: 8.8,
  },
  {
    fav: false,
    name: 'Bernardo Silva',
    club: 'Manchester City',
    position: 'Centrocampista',
    country: 'Portugal',
    age: 29,
    goals: 10,
    assists: 11,
    rating: 8.5,
  },
  {
    fav: false,
    name: 'Alisson Becker',
    club: 'Liverpool',
    position: 'Portero',
    country: 'Brasil',
    age: 31,
    goals: 0,
    assists: 1,
    rating: 8.1,
  },
  {
    fav: false,
    name: 'Rúben Dias',
    club: 'Manchester City',
    position: 'Defensa',
    country: 'Portugal',
    age: 26,
    goals: 2,
    assists: 1,
    rating: 8.2,
  },
];
